version: "3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esd:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: 
      - observability

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.0
    container_name: logstash
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "LOGSTASH_INTERNAL_PASSWORD=logstash"
    ports:
      - 5044:5044
      - 9600:9600
      - "50000:50000/tcp"
      - "50000:50000/udp"
    volumes:
      #- ./logd:/usr/share/logstash
      #- ./logd/csv.conf:/usr/share/logstash/csv.conf:ro
      - ./logd/config:/usr/share/logstash/config
      - ./logd/pipeline:/usr/share/logstash/pipeline
      - ./logd/data:/usr/share/logstash/data
    depends_on:
      - elasticsearch
    networks: 
      - observability
        
networks:
  observability:
    external: true